version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: insight-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insight_leancoffee
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    container_name: insight-server
    depends_on:
      - postgres
    env_file:
      - .env.example
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npx prisma generate && npm run dev"

  web:
    build: ./web
    container_name: insight-web
    depends_on:
      - server
    env_file:
      - .env.example
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    ports:
      - "5173:5173"
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  postgres_data:
